#
# Copyright (c) 2019 IBM
#
# SPDX-License-Identifier: Apache-2.0
#
test:
  - functional
  - docker
  - network
  - ramdisk
  - docker-stability
  - entropy

docker:
  Describe:
    - CPUs and CPU set
    - Hotplug memory
    - memory constraints
  Context:
    - remove bind-mount source before container exits
    - run container exceeding memory constraints
  It:
