#
# Copyright (c) 2019 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: sharevol-kata
  annotations:
    io.kubernetes.cri-o.TrustedSandbox: "false"
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
  - name: test
    image: busybox
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
      - name: host-empty-vol
        mountPath: "/host/cache"
      - name: memory-empty-vol
        mountPath: "/tmp/cache"
  volumes:
  - name: host-empty-vol
    emptyDir: {}
  - name: memory-empty-vol
    emptyDir:
      medium: Memory
      sizeLimit: "50M"
