apiVersion: v1
kind: Pod
metadata:
  name: pod-block-pv
  annotations:
    io.kubernetes.cri-o.TrustedSandbox: "false"
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  runtimeClassName: kata
  containers:
    - name: my-container
      image: debian
      command: ["tail", "-f", "/dev/null"]
      volumeDevices:
        - devicePath: DEVICE_PATH
          name: my-volume
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: block-loop-pvc
