#
# Copyright (c) 2020 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: test-init
spec:
  runtimeClassName: kata
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'date']
  containers:
  - name: test
    image: busybox
    command: [ 'sh', '-c', 'tail -f /dev/null']
restartPolicy: Never
