#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: test-quota-ns
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pod-quota
    namespace: test-quota-ns
  spec:
    hard:
      pods: "2"
      requests.cpu: "3"
      requests.memory: "1Gi"
      limits.cpu: "6"
      limits.memory: "2Gi"
