on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
      - unlabeled

name: Static checks
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GO111MODULE: off
      GITHUB_USER : ${{ secrets.GITHUB_USER }}
      GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install Go
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'force-skip-ci') }}
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.2
    - name: Setup GOPATH
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'force-skip-ci') }}
      run: |
        gopath_org=$(go env GOPATH)/src/github.com/kata-containers/
        mkdir -p ${gopath_org}
        ln -s ${PWD} ${gopath_org}
    - name: Set env
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'force-skip-ci') }}
      run: |
        echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
    - name: Checkout code
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'force-skip-ci') }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: ./src/github.com/${{ github.repository }}
    - name: Install dependencies
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'force-skip-ci') }}
      run: |
        cd ${GOPATH}/src/github.com/kata-containers/tests && ./.ci/setup.sh
    - name: Static checks
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'force-skip-ci') }}
      run: |
        cd ${GOPATH}/src/github.com/kata-containers/tests
        make static-checks
